[workspace]
resolver = "2"
members = [
  "crates/ext-widget-core",
  "crates/ext-widget-bin",
  "crates/ext-widget-lib",
]

[workspace.dependencies]
tokio = { version = "1.35.0" }
anyhow = "1.0.75"
tracing = "0.1.40"

