version = "Two"
unstable_features = true

tab_spaces = 4
edition = "2021"
max_width = 80
wrap_comments = true
group_imports = "StdExternalCrate"

fn_params_layout = "Compressed"

comment_width = 80
empty_item_single_line = false
format_code_in_doc_comments = true
format_strings = true
doc_comment_code_block_width = 80
imports_granularity = "Crate"
format_macro_matchers = true
format_macro_bodies = true
reorder_impl_items = true
