[package]
name = "external-widget"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "external-widget"
path = "src/main.rs"

[dependencies]
external-widget-core = { workspace = true }
external-widget-widgets = { workspace = true }

nvim-rs = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
rmpv = { workspace = true }
headless_chrome = { version = "1.0.8", features = ["fetch"] }
anyhow = "1.0.75"
