[package]
name = "external-widget-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nvim-rs = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
rmpv = { workspace = true }
cosmic-text = { worksapce = true }

