[package]
name = "ext-widget-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }

taffy = { git = "https://github.com/DioxusLabs/taffy", rev = "440843c700455363383e0a4fc365a15deebd4717", features = ["serde"] }
nvim-oxi = { version = "0.4.1", features = ["neovim-nightly"] }
thiserror = "1.0.51"
